[feat] Drag&Drop 구현: Directory
Kernel360/F2-TECHPICK pull request #117
Opened 2024-10-02 09:13 UTC by enigsuss

- Close #70

## What is this PR? 🔍

- 기능 : 우측 화면에서 좌측 directory view로 dnd 구현
- issue : #70 

## Changes 📝
![dnd](https://github.com/user-attachments/assets/4884ef07-f7de-4d33-865c-d6de3aca7a12)

## Precaution

2024-10-02 10:49 UTC, dmdgpdi requested changes
고생하셨습니다! 저도 라이브러리를 학습해야 더 로직을 잘 이해할 수 있을 것 같아요!
아래 영상의 로직이 부자연스러운 것 같아서 의도한 것인지 궁금합니다.

https://github.com/user-attachments/assets/531c4706-cac4-4638-8676-dcb2360da11c

2024-10-02 10:49 UTC, dmdgpdi commented on frontend/techpick/src/widgets/LinkEditorSection/LinkEditorSection.tsx
p4:
33번째 코드는 <div>{'>'}</div> 이건 안되는 이유가 따로 있나요?
```tsx
          <div>
            <Image
              src={`image/ic_sort.svg`}
              alt="search"
              width={24}
              height={24}
            />
          </div>
          <div>
            <Image
              src={`image/ic_search.svg`}
              alt="search"
              width={24}
              height={24}
            />
          </div>
```
해당 코드는 테마 변경시에 보이지 않습니다.  [Lucid Icon](https://lucide.dev/guide/packages/lucide-react) 같은 라이브러리를 써서 색을 바꿔보는건 어떨까요?

2024-10-02 10:49 UTC, dmdgpdi commented on frontend/techpick/src/features/moveNode.ts
> +    // 부모가 같은 위치로 이동 시
p4: updateFocusedFolderNodeList와 같은 주석인데 어떤 차이가 있는지 궁금함.

2024-10-04 04:55 UTC, enigsuss commented on frontend/techpick/src/widgets/LinkEditorSection/LinkEditorSection.tsx
확인, Lucid Icon 적용 완료

2024-10-04 05:15 UTC, enigsuss commented on frontend/techpick/src/features/moveNode.ts
> +    // 부모가 같은 위치로 이동 시
코드가 일부 중복된 것을 확인함, 수정완료

2024-10-04 05:18 UTC, enigsuss commented
> 고생하셨습니다. 저도 라이브러리를 학습해야 더 로직을 잘 이해할 수 있을 것 같아요. 양질의 리뷰를 못해드려 죄송합니다. 또 아래 영상의 로직이 부자연스러운 것 같아서 의도한 것인지 궁금합니다.
> 
>  Oct-02-2024.19-48-08.mp4

감사합니다. 해당 증상은 인지하고 있습니다. 다음 pr에서 해당 부분에 useDrop을 적용해 해결할 예정입니다.

2024-10-04 05:31 UTC, dmdgpdi approved these changes
고생하셨습니다!

2024-10-04 05:45 UTC, merged

2024-10-07 09:32 UTC, dowookims commented on frontend/techpick/package.json
>      "react-hot-toast": "^2.4.1",
이부분 봐주시면 감사하겠습니다.

2024-10-07 09:46 UTC, dowookims commented on frontend/techpick/src/features/Draggable/Folder.tsx
> +      <Image src={`image/ic_folder.svg`} alt="folder" width={64} height={64} />
접근성 측면에서 name + 폴더가 더 나을거 같아요

2024-10-07 09:52 UTC, dowookims commented on frontend/techpick/src/features/moveNode.ts
> +  };
함수로 빼지않고 그냥 호출해도 좋을 것 같습니다.

2024-10-07 09:57 UTC, dowookims reviewed
👍