[FEAT] 폴더 요청 - JSON 파서 구현
Kernel360/F2-TECHPICK pull request #130
Opened 2024-10-03 16:49 UTC by kimminkyeu

- Close #120 

## What is this PR? 🔍
:warning: 파서 구현체는 살짝 더럽습니다.
- 기능 : parser 로직 작성 --> `StructureParserImpl.java` 구현
- issue : #120

2024-10-04 04:45 UTC, Gyaak requested changes
리뷰 확인해주세요

2024-10-04 04:45 UTC, Gyaak commented on backend/src/main/java/kernel360/techpick/feature/folder/service/parser/internal/StructureParserImpl.java
> +			Long idForBackend = null;
p4: `idForBackEnd`대신 `serverId`로 하면 어떨지? `idForFrontEnd`도 마찬가지로 `clientId`로?

2024-10-04 04:45 UTC, Gyaak commented on backend/src/main/java/kernel360/techpick/feature/folder/service/parser/internal/StructureParserImpl.java
> +	) throws IllegalNodeTypeException {
p3: `UnsupportedOperationException`추가 필요..?

2024-10-04 04:45 UTC, Gyaak commented on backend/src/main/java/kernel360/techpick/feature/folder/service/parser/internal/StructureParserImpl.java
> +			);
p4: 뭔가 별도의 메소드로 분리되었으면 좋겠는데 깔끔하게 분리할 방법이 안떠오르네요...
이후 리팩토링에서 좀 고쳐보는걸로..

2024-10-04 06:30 UTC, kimminkyeu commented on backend/build.gradle
> +    implementation 'com.google.code.gson:gson:2.8.9'
없습니다. 최신 버전으로 수정할께요~

2024-10-04 06:33 UTC, kimminkyeu commented on backend/src/main/java/kernel360/techpick/feature/folder/service/parser/internal/StructureParserImpl.java
> +	) throws IllegalNodeTypeException {
GSON 호출 과정에서 발생하는 모든 예외를 Exception으로 받아 통으로 처리할 예정이라 Pass

2024-10-04 06:33 UTC, kimminkyeu commented on backend/src/main/java/kernel360/techpick/feature/folder/service/parser/internal/StructureParserImpl.java
> +			);
넵 당장 떠오르는 방식이 없습니다... 추후 리팩토링 합시다

2024-10-04 07:29 UTC, kimminkyeu commented on backend/src/main/java/kernel360/techpick/feature/folder/service/parser/internal/StructureParserImpl.java
> +			Long idForBackend = null;
좋은 생각인 것 같습니다. 수정하겠ㅅㅂ니다.

2024-10-04 12:03 UTC, sangwonsheep approved these changes
LGTM

2024-10-05 13:16 UTC, closed without merging

2024-10-05 13:17 UTC, kimminkyeu commented
푸시 문제 + 변경 사항이 좀 있어서 새롭게 PR을 날립니다.