[FEAT] FolderService 추가 비즈니스 로직 구현 및 리팩토링
Kernel360/F2-TECHPICK pull request #143
Opened 2024-10-05 10:11 UTC by Gyaak

- Close #141

## What is this PR? 🔍

- 기능 : FolderService 추가 비즈니스 로직 구현 및 리팩토링
- issue : #141

## Changes 📝

### Folder, Pick

`parentFolder`에 `@OnDelete(action = OnDeleteAction.CASCADE)` 어노테이션 추가
부모 폴더 삭제시 별도 delete 메소드 호출 없이 자식 폴더/픽 삭제되기 위함

### FolderService

1. 사용자 기본 폴더 조회 로직 구현
 - 사용자, ROOT, RECYCLE_BIN, UNCLASSIFIED 폴더의 아이디 반환
```
{
  "user" : userId,
  "RECYCLE_BIN" : recycle_bin folder id,
  "UNCLASSIFIED" : unclassified folder id,
  "ROOT" : root folder id
}
```
2. 업데이트 메소드 분리
  - 폴더 이름 변경 : Structure Json 검증 안함
  - 폴더 이동 : Structure Json 검증
3. 삭제 로직 리팩토링
  - 삭제하려는 폴더는 휴지통에 있어야함
  - 삭제한 폴더를 부모로 가지는 모든 폴더/픽도 같이 삭제됨

### FolderProvider

`FolderType findParentBasicFolder(Long folderId)`
- 현재 폴더가 어떤 기본폴더에 속해있는지 반환
- ex) ROOT, RECYLE_BIN, UNCLASSIFIED

Spring Data에서 재귀쿼리를 지원하지 않아 반복조회를 통해 최상위 폴더의 FolderType을 반환

## Precaution

- `Folder`, `Pick` 엔티티 수정이 있으므로 merge이후 pull해주세요

2024-10-05 15:18 UTC, kimminkyeu commented on backend/src/main/java/kernel360/techpick/feature/folder/model/FolderProvider.java
> +			currentFolder = this.findById(currentFolder.getId());
p2: parentFolder의 id로 해야 하는것같은데 확인 부탁
```suggestion
			currentFolder = this.findById(currentFolder.getParentFolder().getId());
```

2024-10-05 15:24 UTC, kimminkyeu commented on backend/src/main/java/kernel360/techpick/feature/folder/service/FolderService.java
p3: validateDuplicateFolderName이 같은 부모 폴더 안에서, 즉 같은 레벨일 때 동일한 이름이 없도록 하는 것으로 생각했는데 --> repository를 보니 전체 구조에서 같은 이름이 존재할 수 없는 것으로 보임.
- 이게 나의 직속 부모가 같은 친구들중에서만 이름이 안겹치면 되는 것 아닌지?

2024-10-05 15:27 UTC, kimminkyeu commented on backend/src/main/java/kernel360/techpick/feature/folder/service/FolderService.java
> +		// StructureValidator validator = StructureValidator.getValidator(userId);
p4: 이 검증은 json에서 value에 대한 유효성 검증이라고 생각하면 되는지?

2024-10-05 15:35 UTC, kimminkyeu commented on backend/src/main/java/kernel360/techpick/feature/folder/service/FolderService.java
> +		// TODO: Validator 구현 후 structure json 검증 로직 추가
그냥 validator 코드만 있으면 처음 보는 사람이 왜 삭제 후에 validate하는지 헷갈릴 것 같아서 그럼

2024-10-05 15:38 UTC, kimminkyeu commented on backend/src/main/java/kernel360/techpick/feature/folder/service/FolderService.java
> +	public Map<String, Long> getBasicFolderIdMap(Long userId) {
p3: 이 함수의 목적은 나중에 클라이언트에게 response json 데이터 보낼 때 사용될 함수인지?

2024-10-05 15:41 UTC, kimminkyeu commented on backend/src/main/java/kernel360/techpick/feature/folder/service/FolderService.java
> +	public Map<String, Long> getBasicFolderIdMap(Long userId) {
p3(질문): 사용자 기본폴더 조회 로직이 어디에 쓰일 예정인지?

2024-10-05 15:41 UTC, kimminkyeu commented on backend/src/main/java/kernel360/techpick/feature/folder/service/FolderService.java
> +	public Map<String, Long> getBasicFolderIdMap(Long userId) {
사용처가 바로 안떠올라서 질문 드림.

2024-10-05 15:43 UTC, kimminkyeu requested changes
코멘트중 `findParentBasicFolder` 부분만 확인 부탁드리며, 답변 주시는 대로 승인 다시 드리겠습니다!

2024-10-06 04:24 UTC, Gyaak commented on backend/src/main/java/kernel360/techpick/feature/folder/model/FolderProvider.java
> +			currentFolder = this.findById(currentFolder.getId());
수정완료

2024-10-06 04:27 UTC, Gyaak commented on backend/src/main/java/kernel360/techpick/feature/folder/service/FolderService.java
기능정의할때 같은 사용자의 폴더와 픽은 유일한 이름을 가진다고 했었음
중복 이름이 필요하다면 논의 후에 수정해야할것으로 보임

2024-10-06 04:27 UTC, Gyaak commented on backend/src/main/java/kernel360/techpick/feature/folder/service/FolderService.java
> +		// StructureValidator validator = StructureValidator.getValidator(userId);
맞아요

2024-10-06 04:41 UTC, Gyaak commented on backend/src/main/java/kernel360/techpick/feature/folder/service/FolderService.java
> +	public Map<String, Long> getBasicFolderIdMap(Long userId) {
기본폴더를 특정 String값으로 보낼 경우 파싱에 어려움 있음
ex) id: RECYCLE_BIN, id: 5 이렇게 같이 오면
서버에서는 둘다 String으로 받아서 분류해줘야함
이를 방지하기 위해 클라이언트에서 사용자의 기본 폴더 id를 받을 수 있는 api를 제공하려고 합니다.

2024-10-06 05:41 UTC, kimminkyeu commented on backend/src/main/java/kernel360/techpick/feature/folder/service/FolderService.java
확인. 이건 새로운 이슈로 남기겠음

2024-10-06 05:41 UTC, kimminkyeu commented on backend/src/main/java/kernel360/techpick/feature/folder/service/FolderService.java
> +	public Map<String, Long> getBasicFolderIdMap(Long userId) {
확인

2024-10-06 05:42 UTC, kimminkyeu approved these changes
LGTM

2024-10-06 08:07 UTC, kimminkyeu commented
@Gyaak 테스트 서버 DB도 테이블 drop했습니다.
constraint 반영하기 위해 제가 머지 진행하겠습니다.

2024-10-06 08:12 UTC, merged