Back/feat/#146
Kernel360/F2-TECHPICK pull request #147
Opened 2024-10-05 13:15 UTC by kimminkyeu

- Close #146 
### :warning: 지난 PR에서 변경된 것이 많고, 푸시가 안되는 이슈도 있어서 새로 만들었습니다.
## What is this PR? 🔍

- 기능 : JSON 형식 변경에 맞춰 jackson 매퍼로 파싱 진행
-  :warning: null 필드, 없는 필드는 모두 에러로 간주
- issue : #146 

NOTE: 리스트로 변환할 때, 루트 디렉토리의 id 값을 넣어야 함.
```java
ClientDirectory clientDirectory = ClientDirectory.fromJson(json);
List<RelationalNode> nodes = clientDirectory.convertRootToNodeList( /* root 폴더의 id를 넣어주세요 */ );
```

2024-10-05 14:55 UTC, Gyaak requested changes
고생하셨습니다.
리뷰 확인 부탁드려요

1. 파싱 관련된 클래스들이 folder 패키지에 있는게 적절하지 않다고 생각함
파싱된 애들을 Folder와 Pick에서 둘다 쓸텐데 별도 패키지로 분리하는게 좋지 않을지..?

2. gson에서 jackson으로 변경한 이유는 여러 조건에 따라 다르게 파싱해야하는 경우 jackson이 더 적합했다..? 정도로 생각하면 될까요?
다른 변경 이유가 있으면 궁금합니다.

2024-10-05 14:55 UTC, Gyaak commented on backend/src/main/java/kernel360/techpick/core/auth/service/CustomOAuth2Service.java
별도 이슈 혹은 해당 PR에 리뷰해주세요

2024-10-05 14:55 UTC, Gyaak commented on backend/src/main/java/kernel360/techpick/feature/folder/exception/ApiFolderErrorCode.java
> +	;
p2: 별도 exception, errorCode를 분리하는게 나을거같음
왜냐면 해당 예외가 `FolderService` `PickService` 둘다에서 모두 발생할것같음

2024-10-05 14:55 UTC, Gyaak commented on backend/src/main/java/kernel360/techpick/feature/folder/service/directory/ClientDirectory.java
p3: 별도 패키지로 분리하는게 좋을듯함

2024-10-05 14:55 UTC, Gyaak commented on backend/src/main/java/kernel360/techpick/feature/folder/service/directory/ClientDirectory.java
> +	}
p4: json 형식 자체에 대한 검증인가요?

2024-10-05 14:55 UTC, Gyaak commented on backend/src/main/java/kernel360/techpick/feature/folder/service/directory/ClientDirectory.java
> +	}
p4: 앞쪽 공백 스타일 조정 필요..?

2024-10-05 14:55 UTC, Gyaak commented on backend/src/main/java/kernel360/techpick/feature/folder/service/directory/internal/ClientNode.java
> +})
p4: 필드값에 따라 적절한 클래스로 매핑해주는 기능이 있었네요
좋은거같아요

2024-10-05 14:55 UTC, Gyaak commented on backend/src/main/java/kernel360/techpick/feature/folder/service/directory/internal/IllegalNodeTypeException.java
p2: `ApiExcetion`하고 왜 구분해서 만들었는지?

2024-10-05 15:48 UTC, kimminkyeu commented on backend/src/main/java/kernel360/techpick/core/auth/service/CustomOAuth2Service.java
관련 PR은 머지 됬기에 별도 Issue로 남기겠습니다.

2024-10-05 15:57 UTC, kimminkyeu commented on backend/src/main/java/kernel360/techpick/feature/folder/exception/ApiFolderErrorCode.java
> +	;
ㅇㅈ. 별도 분리하도록 하겠음.

2024-10-05 16:11 UTC, kimminkyeu commented on backend/src/main/java/kernel360/techpick/feature/folder/service/directory/internal/IllegalNodeTypeException.java
이유 : NodeType을 다른 feature 에서도 쓸 것 같아서.

상세 설명 : 현재 nodeType 변환 에러는 json 파싱 과정에서만 발생하지만, 다른 패키지에서 이 NodeType을 쓰게 될 경우
명시적으로 catch하도록 하기 위해 checked exeption으로 따로 정의함. 
즉 자 이건 직접 캐치해서 각자 도메인쪽 api예외로 던지세요~ 를 유도하고자 함

2024-10-05 16:13 UTC, kimminkyeu commented on backend/src/main/java/kernel360/techpick/feature/folder/service/directory/ClientDirectory.java
분리 완료

2024-10-05 16:19 UTC, kimminkyeu commented on backend/src/main/java/kernel360/techpick/feature/folder/service/directory/ClientDirectory.java
> +	}
수정 완료.

2024-10-05 16:25 UTC, kimminkyeu commented on backend/src/main/java/kernel360/techpick/feature/folder/service/directory/ClientDirectory.java
> +	}
네 json 형식 자체에 대한 검증입니다.  null 필드, 있어야 하는데 없는 필드, 비어있는 문자열 등을 체크합니다.

2024-10-05 16:34 UTC, kimminkyeu commented
1. 넵 디렉토리 패키지로 이동했습니다.
    디렉토리 안에 폴더, 픽이 있다고 생각해서 이렇게 네이밍했습니다.

2. Jackson이 클래스만 잘 만들어두면 json을 자동 매핑해주기 때문에 
    json 구조 변경에 유연해서 바꿨습니다.
    실제로 gson으로 했을 땐 하드 코딩 느낌이 있었는데, jackson으로 하니 하드 코딩이 싹 없어져서
    제가 보기엔 더 코드가 깔끔해졌습니다.

2024-10-05 16:46 UTC, kimminkyeu commented
@Gyaak 수정했으니 확인 부탁드립니다~

2024-10-05 16:53 UTC, kimminkyeu commented
> 1. 파싱 관련된 클래스들이 folder 패키지에 있는게 적절하지 않다고 생각함
>    파싱된 애들을 Folder와 Pick에서 둘다 쓸텐데 별도 패키지로 분리하는게 좋지 않을지..?
넵 디렉토리 패키지로 이동했습니다.
 디렉토리 안에 폴더, 픽이 있다고 생각해서 이렇게 네이밍했습니다.
> 2. gson에서 jackson으로 변경한 이유는 여러 조건에 따라 다르게 파싱해야하는 경우 jackson이 더 적합했다..? 정도로 생각하면 될까요?
>    다른 변경 이유가 있으면 궁금합니다.
외부 라이브러리를 최대한 지우고 싶어서 jackson으로 변경했습니다.
찾아보니 gson도 다형성 기반 json 파싱 지원하더군요. 
- [gson-polymorphism](https://www.baeldung.com/gson-polymorphism)
둘다 써보니 사용성에선 둘 차이를 모르겠습니다. 둘다 좋은 것 같아요.
성능 차이는 아직 잘 모르겠습니다. 그냥 원하는 거 써도 될 것 같아요...

2024-10-06 04:19 UTC, Gyaak approved these changes
LGTM

2024-10-06 07:26 UTC, merged