[REFACTOR] UserService 구현 포함, 전체 코드 리팩토링
Kernel360/F2-TECHPICK pull request #180
Opened 2024-10-09 13:30 UTC by kimminkyeu

- Close #ISSUE_NUMBER

## What is this PR? 🔍

- 기능 : 
   1. `UserService` 구현을 통해 userId 검증 중복 로직 제거
   2. Mapper에 의존성 제거
   3. 서로 다른 도메인은 오직 서비스만 주입받도록 설정
   4. DB 데이터 캐싱을 위한 1급 컬렉션은 `___Proxy` 로 명명 통일
- issue : #170

2024-10-09 16:38 UTC, Gyaak requested changes
고생하셨습니다... 예상했던것보다 리팩토링할게 훨씬 많았네요..
리뷰 확인부탁드려요

2024-10-09 16:38 UTC, Gyaak commented on backend/src/main/java/kernel360/techpick/core/model/user/User.java
> +	// 소셜 제공자 folderId
p3: 어떤 의미일까요..? providerId 의 오타가 아닐지..

2024-10-09 16:38 UTC, Gyaak commented on backend/src/main/java/kernel360/techpick/core/model/user/SocialType.java
> +	NONE("none"); // 자체 가입 회원
p2: 소셜로그인만 제공할 예정인데 자체 가입 회원을 따로 둔 이유가 궁금

2024-10-09 16:38 UTC, Gyaak commented on backend/src/main/java/kernel360/techpick/feature/folder/model/FolderMapper.java
>  	}
p2: FolderType의 경우 유저가 선택하는 것이 아닌데 굳이 매개변수로 받아서 실수를 유발하게 해야할지 고민해봐야할듯
차라리 FolderType별로 생성 메소드를 분리하는게 좋지 않을지?

2024-10-09 16:38 UTC, Gyaak commented on backend/src/main/java/kernel360/techpick/core/model/folder/StructureJson.java
> +	private Structure<ServerNode> structure;
p2: 현재 db에 저장된 json 안의 값을 조회하거나 변경하는 로직이 없는데 굳이 json타입으로 db에 저장해야할지?

2024-10-09 16:38 UTC, Gyaak commented on backend/src/main/java/kernel360/techpick/feature/structure/service/StructureService.java
> +		var recycleBin = folderStructureService.getRecycleBinByUser(user);
p3: 일관성있게 Folder or var로 통일시켜주세요

2024-10-09 16:49 UTC, sangwonsheep requested changes
리팩토링이 많이 진행되었네요! 
고생많으셨습니다!!! 해당 pr merge 되면 리팩토링 된 양식 따라서 수정하겠습니다.
리뷰에 수정할 사항 몇 개 적어두었으니 확인 부탁드려요

2024-10-09 16:49 UTC, sangwonsheep commented on backend/src/main/java/kernel360/techpick/feature/pick/validator/PickValidator.java
>  			throw ApiPickException.PICK_UNAUTHORIZED_ACCESS();
p1: `!Objects.equals()` 로 변경 필요. ! 빠졌음.

2024-10-09 16:49 UTC, sangwonsheep commented on backend/src/main/java/kernel360/techpick/feature/structure/model/StructureDataProxy.java
> +
p4: 이 클래스가 어디에 어떻게 쓰이는 것인지 모르겠음... 설명 부탁!!

2024-10-09 16:49 UTC, sangwonsheep commented on backend/src/main/java/kernel360/techpick/feature/folder/exception/ApiFolderErrorCode.java
> +		("F0-005", HttpStatus.NOT_ACCEPTABLE, "기본 폴더는 1개만 존재할 수 있음.", ErrorLevel.MUST_NEVER_HAPPEN()),
p1: F0-006으로 변경 필요

2024-10-10 02:19 UTC, kimminkyeu commented on backend/src/main/java/kernel360/techpick/core/model/user/SocialType.java
> +	NONE("none"); // 자체 가입 회원
제거 완료

2024-10-10 02:20 UTC, kimminkyeu commented on backend/src/main/java/kernel360/techpick/core/model/user/SocialType.java
> +	NONE("none"); // 자체 가입 회원
이유는 리팩토링 하면서 아 그럼 여기 추가되면 되겠지 하고 넣은것 뿐이라, 빼겠습니다.

2024-10-10 02:26 UTC, kimminkyeu commented on backend/src/main/java/kernel360/techpick/feature/folder/model/FolderMapper.java
>  	}
1. 이미 폴더 엔티티에서 타입별로 생성함수를 나눔.
2. Enum이기 때문에 실수가 발생하지 않을 거라 판단하였음.
3. folder service의 `createBasicFolders` 에서 BasicFolderType enum set을 활용할 때 이 방식으로 해야 코드가 간결해짐.

2024-10-10 02:28 UTC, kimminkyeu commented on backend/src/main/java/kernel360/techpick/core/model/folder/StructureJson.java
> +	private Structure<ServerNode> structure;
현재 저희 코드는 DB에서 꺼내면 무조건 Deserialize 함. + 클라이언트에게 보낼때 데이터 삽입도 진행함. 쌩 json을 그대로 저장/조회만 하는 경우가 코드에서 없기 때문에, 
위와 같이 자동으로 mapping되도록 하였음.

2024-10-10 02:29 UTC, kimminkyeu commented on backend/src/main/java/kernel360/techpick/core/model/user/User.java
>  	private String nickname;
현재 닉네임은 중복이 발생함. 나중에 중복 발생 안되는 로직이 생기면 그때 유니크 거는게 좋다고 봄.

2024-10-10 02:29 UTC, kimminkyeu commented on backend/src/main/java/kernel360/techpick/feature/tag/model/TagMapper.java
>  			tag.getName(),
대면 확인 완료. 변경하겠음.

2024-10-10 02:57 UTC, kimminkyeu commented on backend/src/main/java/kernel360/techpick/feature/structure/model/StructureDataProxy.java
> +
대면 확인함

2024-10-10 02:57 UTC, kimminkyeu commented on backend/src/main/java/kernel360/techpick/feature/pick/validator/PickValidator.java
>  			throw ApiPickException.PICK_UNAUTHORIZED_ACCESS();
감사감사

2024-10-10 02:58 UTC, kimminkyeu commented on backend/src/main/java/kernel360/techpick/feature/folder/exception/ApiFolderErrorCode.java
> +		("F0-005", HttpStatus.NOT_ACCEPTABLE, "기본 폴더는 1개만 존재할 수 있음.", ErrorLevel.MUST_NEVER_HAPPEN()),
변경 완료

2024-10-10 03:03 UTC, sangwonsheep approved these changes
수정 확인하였습니다!

2024-10-10 03:16 UTC, Gyaak approved these changes
LGTM

2024-10-10 05:04 UTC, merged