[FEAT] pick v2 도메인 개발
Kernel360/F2-TECHPICK pull request #278
Opened 2024-10-20 07:57 UTC by kimminkyeu

- Close #265 

## What is this PR? 🔍

- 기능 : pick 도메인 개발 및 필요한 리더 구현
- issue : #265

2024-10-20 08:17 UTC, kimminkyeu commented on backend/src/main/java/kernel360/techpick/core/model/pick/Pick.java
>  	private String title;
`String title = "";` 으로 수정 예정

2024-10-20 08:26 UTC, Gyaak requested changes
리뷰 확인 부탁드려요.

2024-10-20 08:26 UTC, Gyaak commented on backend/src/main/java/kernel360/techpick/feature/domain/pick/service/PickServiceImpl.java
> +            originFolder.updateChildPickOrder(command.pickId(), command.orderIdx());
p3: PickOrder 업데이트 로직이 엔티티에 들어가있는게 좀 애매하네요..
주석으로 `TODO: 리팩토링 필요` 적어주시면 좋을거같아요

2024-10-20 08:26 UTC, Gyaak commented on backend/src/main/java/kernel360/techpick/feature/infrastructure/folder/reader/FolderReader.java
> +    Folder read(User user, Long folderId);
p2: 조회 메소드명을 read로 통일하고 오버로드해서 사용하실 예정이신가요?

2024-10-20 08:38 UTC, Gyaak requested changes
픽 순서 업데이트 로직 확인부탁드려요.

2024-10-20 08:38 UTC, Gyaak commented on backend/src/main/java/kernel360/techpick/core/model/folder/Folder.java
> +		}
p2: destination이 null인경우가 있을까요?
그리고 만약 null이 들어온다면 예외를 발생시켜야하지 않나요?

2024-10-20 08:38 UTC, Gyaak commented on backend/src/main/java/kernel360/techpick/core/model/folder/Folder.java
> +		return this;
p1: `newOrderList`가 폴더에 반영되지 않은것같음..

2024-10-20 08:38 UTC, Gyaak commented on backend/src/main/java/kernel360/techpick/core/model/folder/Folder.java
> +		}
p1: 범위가 두개 케이스에 따라 달라질 수 있음.

case1) 같은 폴더 내에서 순서 변경
-> 가능한 범위는 `0 ~ childPickOrderList.size() - 1`

case2) 다른 폴더에서 현재 폴더로 이동
-> 가능한 범위는 `0 ~ childPickOrderList.size()`

2024-10-20 08:40 UTC, Gyaak commented
PR이 너무 큰것같습니다.. infra쪽하고 service로직은 pr을 분리했어야 할거같아요..

2024-10-20 09:37 UTC, sangwonsheep commented on backend/src/main/java/kernel360/techpick/core/model/pick/Pick.java
> +	}
p3: 정적 팩토리 메서드 대신 빌더를 도입하게 된 이유?

2024-10-20 09:39 UTC, sangwonsheep commented on backend/src/main/java/kernel360/techpick/feature/domain/pick/dto/PickMapper.java
> +    PickResult.Read toReadResult(Pick pick);
`@Mapping`에 대해 설명 가능한지?

2024-10-21 01:38 UTC, Gyaak commented on backend/src/main/java/kernel360/techpick/core/model/folder/Folder.java
> +		}
PickApiSpecification 명세 수정 line 25

2024-10-21 03:00 UTC, Gyaak approved these changes
LGTM

2024-10-21 03:00 UTC, merged