[FEAT] Folder Domain/Infrastructure 구현
Kernel360/F2-TECHPICK pull request #284
Opened 2024-10-21 12:04 UTC by Gyaak

- Close #277

## What is this PR? 🔍

- 기능 : Folder Domain/Infrastructure 구현
- issue : #277

## Changes 📝

2024-10-22 11:02 UTC, Gyaak commented
@kimminkyeu @sangwonsheep 
리뷰.. 해주세요...

2024-10-22 11:05 UTC, kimminkyeu commented
오늘 밤 안에 리뷰 남기겠습니다!

2024-10-22 13:58 UTC, kimminkyeu approved these changes
LGTM. 픽이랑 흐름이 비슷하네요..! 이 부분도 나중에 로직을 묶일 수 있겠다 싶어요.

2024-10-23 01:33 UTC, sangwonsheep requested changes
수정 필요

2024-10-23 01:33 UTC, sangwonsheep commented on backend/src/main/java/kernel360/techpick/feature/infrastructure/folder/reader/FolderReaderImpl.java
> +		}
p1: user, parentFolder 비교하는 중 수정 필요

2024-10-23 01:48 UTC, sangwonsheep approved these changes
LGTM

2024-10-23 03:45 UTC, merged