[FEAT] JSON 파싱 관련 예외 추가 및 요청-응답 로깅 필터 구현
Kernel360/F2-TECHPICK pull request #417
Opened 2024-11-09 16:33 UTC by Gyaak

- Close #390

## What is this PR? 🔍

- 기능 : JSON 파싱 관련 예외 추가 및 요청-응답 로깅 필터 구현
- issue : #390

## Changes 📝

### JSON 파싱 관련 예외 추가
기존에는 Json 형식에 오류가 있어 파싱 실패시 500에러가 발생
-> 프론트에서 예외처리 하기 힘듬
이를해결하기위해
- Json 파싱 실패 시 발생하는 `HttpMessageNotReadableException`을 처리할 수 있는 ExceptionHandler 추가
- `INVALID_JSON_ERROR` 추가

### 요청 - 응답 로깅을 위한 필터 추가
각 api별 호출 횟수 및 실행시간을 측정하기 위한 `ApiRequestResponseLoggingFilter`구현
`/api/`로 시작되는 요청의 다음 정보들을 로깅
- URL
- HTTP Method
- 실행시간

2024-11-10 04:32 UTC, kimminkyeu commented on backend/techpick-core/src/main/java/techpick/core/exception/base/ApiExceptionHandler.java
> +	public ApiErrorResponse handleHttpMessageNotReadableException(HttpMessageNotReadableException exception) {
p1. 로깅 코드 추가 부탁
```suggestion
	ErrorLevel.SHOULD_NOT_HAPPEN().handleError(exception);
```

2024-11-10 04:42 UTC, kimminkyeu commented on backend/techpick-api/src/main/java/techpick/api/filter/ApiRequestResponseLoggingFilter.java
> +			filterChain.doFilter(request, response);
p4: try 구문은 필터 통과 ,즉 request를 실행하는 흐름이고, finally 구문은 response로 나가는 흐름인지?

2024-11-10 04:45 UTC, kimminkyeu commented
LGTM.  코멘트 부분만 반영 부탁드립니다.
+) 성능 관찰이 필요한 서비스 메소드는 커스텀 어노테이션으로
호출 시작, 리턴까지의 시간을 로깅할 수 있으면 좋을듯?

2024-11-10 04:46 UTC, kimminkyeu requested changes
코멘트 남겼습니다.

2024-11-10 06:36 UTC, sangwonsheep approved these changes
고생하셨습니다! Json 파싱 예외도 고려한 점 좋습니다

2024-11-10 07:23 UTC, Gyaak commented on backend/techpick-api/src/main/java/techpick/api/filter/ApiRequestResponseLoggingFilter.java
> +			filterChain.doFilter(request, response);
네 맞습니다.
응답이 나가기 전에 다시 필터를 거치게 되는데 그때 finally 블록 안의 코드가 실행됩니다.

2024-11-13 06:36 UTC, Gyaak commented
ELK스택을 붙이며 로깅이 새로 추가될 예정
Request/Response에 대한 로그는 NGINX에서 받을 예정

JSON parsing error exception handler는 다른 pr에서 추가할예정

2024-11-13 06:36 UTC, closed without merging