feat: 페이지 기본 요소 렌더링
Kernel360/F2-TECHPICK pull request #52
Opened 2024-09-25 09:46 UTC by enigsuss

- Close #29 

## What is this PR? 🔍

- 기능 : 기본 구조 및 directory, folder, link 요소를 렌더링했습니다.
- issue : #29

## Changes 📝
![image](https://github.com/user-attachments/assets/476e626a-4ad3-47bd-8105-b750a83814b2)

## Precaution
- 우측 화면의 폴더, 링크 표시 방식 변경 예정입니다.

2024-09-25 11:53 UTC, dmdgpdi requested changes
고생하셨습니다! 테마를 적용한 걸 보니까 저도 테마를 적용하고 싶네요!

2024-09-25 11:53 UTC, dmdgpdi commented on frontend/techpick/src/components/DirNode/DirNode.tsx
> +export const DirNode: FC<DirNodeProps> = ({ node, style, dragHandle }) => {
p1: `export const DirNode = ({ node, style, dragHandle }: DirNodeProps) => {`
이런식으로 변경하는 건 어떰?
[참고 링크](https://yceffort.kr/2022/03/dont-use-react-fc)

2024-09-25 11:53 UTC, dmdgpdi commented on frontend/techpick/src/components/DirNode/DirNode.tsx
p3: DirNode가 아닌 DirectoryNode 는 어떰? 축약보다 명확한 의미가 좋은 것 같음.

2024-09-25 11:53 UTC, dmdgpdi commented on frontend/techpick/src/lib/themes/reset.css.ts
p3: lib 안에 말고, 따로 themes로 뺴는 건 어떰?

2024-09-25 11:53 UTC, dmdgpdi commented on frontend/techpick/src/lib/themes/themeDark.css.ts
> +  },
p3: theme과 관계없이 공통적인 부분은 하나로 관리해도 될 것 같음. 이런 방식은 어떰?
```
export const commonSpace = {
  xs: '4px',
  sm: '8px',
  md: '16px',
  lg: '24px',
  xl: '32px',
};

export const darkThemeClass = createTheme({
  color: {
    primary: '#00306e',
    secondary: '#95004d',
    border: '#eaeaea',
    background: '#000',
  },
  space: {
    ...commonSpace, // 공통 space를 확장
  },
  breakpoints: {
    mobile: '576px',
    tablet: '768px',
    desktop: '1024px',
  },
});
```

2024-09-25 11:53 UTC, dmdgpdi commented on frontend/techpick/src/app/layout.tsx
> +import { ThemeProvider } from '@/lib/providers/ThemeProvider';
p3: ToastProvider와 ThemeProvider는 providers에서 나오는 것도 괜찮을 것 같음. providers/index.ts 폴더를 만드는 건 어떰?

2024-09-25 11:53 UTC, dmdgpdi commented on frontend/techpick/src/lib/types/NodeData.ts
p2: type도 lib에 넣기보다는 types폴더를 만드는 것도 좋을 것 같음. 또 공통적인 type이 아니라면 컴포넌트와 같이 있는 건 어떰?

2024-09-25 11:53 UTC, dmdgpdi commented on frontend/techpick/src/widgets/DirView/DirView.tsx
p3: DirView도 좋지만 DirectoryPage는 어떰? 아니면 아예 app/page.tsx에 해당 컴포넌트 전체가 이동하는 것도 좋아보임

2024-09-25 11:53 UTC, dmdgpdi commented on frontend/techpick/src/app/page.tsx
>  export default function Home() {
p3: Home도 좋지만 DirectoryPage처럼 더 명확한 네이밍은 어떰?

2024-09-25 11:53 UTC, dmdgpdi commented on frontend/techpick/src/widgets/DirView/DirView.tsx
> +      <div className={viewContainer}>
p2: Wrapper보다는 Container가 바깥에 있는 건 어떰? 그리고 둘다 감싸는 역할이라면 div는 하나만 있어도 될 것 같음.

2024-09-25 11:53 UTC, dmdgpdi commented on frontend/techpick/src/widgets/LeftSection/LeftSection.tsx
> +const LeftSection: FC<LeftSectionProps> = ({ setFocusedNode }) => {
p2: FC를 써야하는 이유가 있는지 궁금함

2024-09-25 11:53 UTC, dmdgpdi commented on frontend/techpick/src/widgets/LeftSection/LeftSection.tsx
> +            // renderCursor={DirCursor}
p3: 주석이 있다면 해당 주석이 왜 있는지 명세 해주는 건 어떰?

2024-09-25 11:53 UTC, dmdgpdi commented on frontend/techpick/src/widgets/MiddleSection/MiddleSection.tsx
> +} from '@/widgets/DirView/dirview.css';
p2: 해당 css를 같이 쓴다면 폴더를 나누는 것보다는 DirView에 LeftSection, MiddleSection등이 같이 들어있는 건 어떰?

2024-09-25 11:53 UTC, dmdgpdi commented on frontend/techpick/src/widgets/MiddleSection/MiddleSection.tsx
> +export default MiddleSection;
p3: 이거 컴포넌트명을 바꾸면 두번 바꿔야함. export default를 맨 위에 두는 건 어떰?

2024-09-26 01:37 UTC, enigsuss commented on frontend/techpick/src/app/page.tsx
>  export default function Home() {
그렇다면, MainPage는 어떰?

2024-09-26 01:43 UTC, enigsuss commented on frontend/techpick/src/widgets/DirView/DirView.tsx
app/page.tsx에서 작업하다가 코드가 커져서 컴포넌트로 분리했었음
Dir과 Bookmark, 추후에는 Recommand까지 포함될 예정이라, 
이름을 MainView로 바꾸는 것은 어떰?

2024-09-26 01:46 UTC, enigsuss commented on frontend/techpick/src/app/style.css.ts
> +export const rootWrapper = style({
죄송. Wrapper와 Container의 용도를 반대로 이해하고 있었음. 수정함!

2024-09-26 06:34 UTC, enigsuss commented on frontend/techpick/src/lib/themes/themeDark.css.ts
> +  },
공통적인 부분 분리함. 수정완료

2024-09-26 06:35 UTC, enigsuss commented on frontend/techpick/src/widgets/LeftSection/LeftSection.tsx
> +            // renderCursor={DirCursor}
나중에 사용하려고 작성함, 주석 제거 완료

2024-09-26 07:47 UTC, dmdgpdi requested changes
고생하셨습니다. 방금 이야기한대로 폴더 내에 메인 컴포넌트는 index로 통일해주시면 좋을 것 같습니다!

2024-09-26 07:47 UTC, dmdgpdi commented on frontend/techpick/src/app/layout.tsx
p1: `import { ToastProvider,ThemeProvider } from '@/providers';` 수정 부탁.

2024-09-26 07:47 UTC, dmdgpdi commented on frontend/techpick/src/widgets/LeftSection/LeftSection.tsx
> +import { DirectoryNode } from '@/components/DirectoryNode/DirectoryNode';
p1: index.tsx 수정 요망.

2024-09-26 07:48 UTC, dmdgpdi approved these changes

2024-09-26 07:49 UTC, dmdgpdi requested changes
index.tsx만 바꿔주세요!

2024-09-26 08:16 UTC, enigsuss reviewed
수정완료

2024-09-26 08:16 UTC, enigsuss commented on frontend/techpick/src/widgets/LeftSection/LeftSection.tsx
> +import { DirectoryNode } from '@/components/DirectoryNode/DirectoryNode';
확인, 수정완료

2024-09-26 11:25 UTC, dmdgpdi requested changes

2024-09-26 11:25 UTC, dmdgpdi commented on frontend/techpick/src/lib/icons/ic_arrow_down.svg
p1: svg파일은 root폴더의 public폴더에 있는 것이 좋을 것 같음.
[nextjs 공식문서](https://nextjs.org/docs/app/building-your-application/optimizing/static-assets)

2024-09-26 11:25 UTC, dmdgpdi commented on frontend/techpick/src/widgets/LeftSection/LeftSection.tsx
p1: 이름 변경 부탁! 어떤 부분인지 더 명확하면 좋을 듯

2024-09-26 13:18 UTC, dmdgpdi approved these changes
고생!!!! 명확해서 너무 좋음!!!!

2024-09-26 13:18 UTC, merged