[REFACTOR] 분산 락이 되지 않는 문제 해결 및 서비스에 분산 락 추가
Kernel360/F2-TECHPICK pull request #687
Opened 2024-12-06 07:44 UTC by sangwonsheep

- Close #677

## What is this PR? 🔍

- 기능 : 분산 락 문제 해결 및 분산 락이 필요한 곳에 추가
- issue : #677

## Changes 📝
- 분산 락이 트랜잭션 범위 안으로 들어가게 되어 락이 제대로 동작하지 않는 문제 해결
  - `LoginUserIdDistributedLockAspect`에 `@Order(1)` 추가하여 aop 우선순위를 가장 높게 설정
- Lock 설정, 해제 메서드에 트랜잭션 추가
- `@LoginUserId` 어노테이션을 aop에 사용 시 aop가 동작하지 않는 문제 해결
  - `ArgumentResolver` 동작과 `aop` 동작이 꼬이면서 발생하는 것으로 추정
  - 해당 어노테이션 제거 후 리플렉션으로 `userId` 가져오도록 변경
- 분산 락 어노테이션에 키 설정하는 필드 제거
  - 리플렉션으로 메서드명 가지고 온 후 `메서드 명_userId`로 키 설정 -> ex) `deleteFolder_1`

## Precaution
- 필요한 메서드에서 추가로 락 어노테이션 붙일 예정
  - 필요한 부분 생각 후 추가하도록 하겠습니다. (~12/7(토))

2024-12-06 08:03 UTC, Gyaak requested changes
고생하셨습니다.
리뷰 확인부탁드려요.

2024-12-06 08:03 UTC, Gyaak commented on backend/techpick-api/src/main/java/techpick/api/infrastructure/lock/LockService.java
p2: `LockService` 클래스를 추가한 이유가 궁금합니다.

2024-12-06 09:00 UTC, kimminkyeu approved these changes
p3: 고생하셨습니다!
저도 해결 방안이 떠오르지 않아 일단 의견만 남기면, 
협업할 때 어노테이션 붙이고 userId를 파라미터로 넣는걸 깜빡하는 경우가 발생할 수 있을 것 같아요. 
물론 @UserId로 획득하는게 잘 안되서 이렇게 변경된 것도 잘 알고 있습니다.
AOP 를 쓰다 보니 이런 부분에서 불편함이 생기는 것 같습니다.
이 부분은 추후 개선책으로 남기고자 백엔드 TODO에 추가하겠습니다.
#631

2024-12-06 09:08 UTC, kimminkyeu commented on backend/techpick-api/src/main/java/techpick/api/infrastructure/lock/LockService.java
p2: 저도 궁금합니다!

2024-12-08 06:00 UTC, sangwonsheep commented on backend/techpick-api/src/main/java/techpick/api/infrastructure/lock/util/LoginUserIdDistributedLockAspect.java
> +			}
PickTag 테이블의 경우, 비로그인 사용자에 대해 락을 거는 경우가 있을 수 있습니다.

2024-12-08 06:40 UTC, sangwonsheep commented on backend/techpick-api/src/main/java/techpick/api/infrastructure/lock/LockService.java
`@Transactional(propagation = Propagation.REQUIRES_NEW)`를 이용하여 락에 대한 트랜잭션을 분리하고자 하였습니다.
제거하고 테스트해보았을 때, 락이 제대로 걸리는 것을 보게 되어 트랜잭션을 유지해뒀던 것 같습니다.

락에는 트랜잭션 없이도 락이 제대로 걸리는 것을 확인했기 때문에 해당 트랜잭션 제거하도록 하겠습니다.

https://developer-nyong.tistory.com/76
https://techblog.woowahan.com/2631/

2024-12-08 07:05 UTC, sangwonsheep commented
@Gyaak 리뷰 내용 확인하신 후 승인해주시면 감사하겠습니다!

2024-12-08 11:05 UTC, Gyaak commented on backend/techpick-api/src/main/java/techpick/api/infrastructure/lock/util/LoginUserIdDistributedLockAspect.java
> +			}
잘 이해가 되지 않아 내일 스크럼때 한번 더 설명해주시면 감사합니다!

2024-12-09 01:25 UTC, merged