[feat] 태그 API 구현
Kernel360/F2-TECHPICK pull request #71
Opened 2024-09-27 15:43 UTC by Gyaak

- Close #38

## What is this PR? 🔍

- 기능 : Tag Api 구현
- issue : #38 

## Changes 📝

### TagService
- `createTag`: 태그 생성
  - 가장 최후 순서(biggest order)로 태그 생성
- `getTagListByUser`: 사용자가 생성한 태그 목록 조회
- `updateTagList`: 태그 목록 수정
  - 변경이 일어난 모든 태그를 list로 받아 해당 db에 적용
- `deleteById`: 태그 삭제
  - 해당 태그를 선택한 픽(Pick)이 존재하면 삭제 불가
- `validateTagAccess`: 사용자가 태그 소유자인지 검증
- `validateTagNameExists`: 태그명이 이미 존재하지는지 검증
- `validateTagHasPick`: 해당 태그를 선택한 픽이 존재하는지 검증

### TagProvider
- TagService와 TagRepository 중간다리 역할을 하는 클래스
- 엔티티 생성 삭제 조회 등의 책임을 가짐

### TagMapper
- dto <-> entity 변환의 책임을 가지는 클래스

## Precaution
- 태그 삭제 시 검증을 위해 임시로 PickTagRepository 구현 PickTagProvider 구현 이후 수정 필요 @sangwonsheep

2024-09-28 06:19 UTC, kimminkyeu commented on backend/src/main/java/kernel360/techpick/feature/tag/controller/TagController.java
> +	private Long getUserId(Authentication authentication) {
p2: 이런 방법으로 하면 어떨지?
```suggestion
	// 방법 1. Security Context Holder를 주입받아 사용 
    SecurityContextHolder.getContext().getAuthentication().getName();

    // 방법 2. (더 나은 방법) 우리 서비스에 맞게 `AuthService` `UserPrincipal`를 상속 구현, 여기서 사용자 인증 정보를 획득
    //        - 참고 : https://stackoverflow.com/questions/14823761/spring-mvc-getting-principal-from-security-context-in-service-layer
    UserPrincipal principal = AuthService.getUserPrincipal();
    principal.getUserId();
    principal.getRole();
```

2024-09-28 06:34 UTC, kimminkyeu commented on backend/src/main/java/kernel360/techpick/feature/tag/service/TagService.java
> +		validateTagNameExists(userId, request.name());
p2: 이 검증은 provider 에서 책임지는게 맞다고 판단.
이 함수 내부에서 provider를 호출한 뒤에 다시 throw하는 것보다
provider에서 exception 없이 들어온 데이터는 모두 유효한 데이터로 처리하는게 어떨찌.

--> 제안: valicateTagNameExist를 따로 파지 말고, 이 로직을 provider 내부에서 처리

2024-09-28 06:38 UTC, kimminkyeu commented on backend/src/main/java/kernel360/techpick/feature/tag/service/TagService.java
> +		validateTagHasPick(tagId);
p2: tag를 지우면, pick에 정해둔 tag도 지워지는게 맞다고 생각함.
사용자가 쓰다보면 tag가 많아질 텐데, 이때는 pick마다 설정된 tag가 많아지고, 따라서 pick이 있어서 삭제 못한다고 메시지 나오면 불편할 듯.

--> 제안: tag 삭제는 무조건 가능하고, 삭제하면 pick에 설정된 해당 tag가 삭제되는 것이 어떨지? (현재 노션이 이 방식을 따름)

2024-09-28 07:02 UTC, kimminkyeu commented on backend/src/main/java/kernel360/techpick/feature/pick/repository/PickTagRepository.java
> +	boolean existsByTag_Id(Long tag_id);
p1: 엔티티 부분 수정 필요 --> pick_tag 테이블에 사용자가 빠지고, pick이 추가해야 할 것 같음.

2024-09-28 08:17 UTC, kimminkyeu commented on backend/src/main/java/kernel360/techpick/feature/tag/service/TagService.java
> +		validateTagHasPick(tagId);
추가 :
이미 존재하는 테이블에 ON DELETE CONTRAINT 추가 하는 방법
- Contraint를 지웠다가 다시 넣는다.
https://stackoverflow.com/questions/1571581/how-to-add-on-delete-cascade-in-alter-table-statement

2024-09-28 08:59 UTC, kimminkyeu commented on backend/src/main/java/kernel360/techpick/feature/tag/service/TagService.java
> +			tagMapper.updateTag(req, targetTag);
p3: (질문) 현재 코드 구현상, order에 대한 제어권은 프론트가 책임지는 걸로 봐도 될지?
(=프론트가 순서가 변경되는 부분을 관리하고, 서버는 그대로 저장만 하는 것으로 이해함)
참고 - https://github.com/Kernel360/F2-TECHPICK/discussions/62
만약 그렇다면, 프론트에서 잘못된 order값을 보냈을 때 검증을 백에서 해주는게 추가되어야 할듯.
ex. 
```typescript
// (1) 동일한 순서가 들어온 경우, 복구가 필요한 예외 발생
{
  "userId": 2,
  "tags": [
    { 
      "id": 10, 
      "name": "react1", 
      "order": 3 
    },
    { 
      "id": 23, 
      "name": "spring2", 
      "order": 3
    },
  ]
}

// (2) 이미 순서가 있는 값에 생성/수정 요청이 들어온 경우
//     ex. 5번째가 이미 존재하는 경우
{
  "userId": 2,
  "tags": [
    { 
      "id": 23, 
      "name": "spring2", 
      "order": 5 // 이미 순서 5에 값이 있음.
    },
  ]
}

// (3) null이 들어온 경우 
{
  "userId": 2,
  "tags": [
    { 
      "id": 23, 
      "name": "spring2", 
      "order": null
    },
  ]
}
```

2024-09-28 09:03 UTC, kimminkyeu requested changes
리뷰 마치겠습니다. 
작성자님 검토가 필요한 부분 코멘트에 남겼습니다.
고생하셨습니다!

2024-09-28 12:14 UTC, Gyaak commented on backend/src/main/java/kernel360/techpick/feature/tag/controller/TagController.java
> +	private Long getUserId(Authentication authentication) {
방법1의 경우 현재와 동일: 컨트롤러에 `Authentication` 타입 파라미터가 있는 경우 스프링이 자동으로 `SecurityContext`에 존재하는 `Authentication` 을 주입

방법2의 경우 좀더 깔끔한 방법 있는지 확인해봄
현재의 방식으로 `controller`에 인증정보에서 `userId`를 가져오는 방식은 매우 불편하다고 생각

2024-09-28 12:18 UTC, Gyaak commented on backend/src/main/java/kernel360/techpick/feature/tag/service/TagService.java
> +		validateTagNameExists(userId, request.name());
`provider`는 `repository`의 데이터를 제공하는 책임만 가져야 한다고 생각하여 분리한것

2024-09-28 12:28 UTC, Gyaak commented on backend/src/main/java/kernel360/techpick/feature/tag/service/TagService.java
> +		validateTagHasPick(tagId);
리뷰를 보고 생각해보니 Tag를 삭제하면, 이미 Pick에 설정된 Tag가 삭제되는것이 더 직관적이라고 생각됨.
-> 직접 `PickTag`테이블에 delete 날리는 방식으로 구현 예정
 
1 . hibernate cascade를 사용하려면 양방향 연관관계여야하므로 현재 엔티티 구조에서는 불가능
2. ddl에서 `ON DELETE CONSTRAINT` 제약조건을 거는것은 FK관계가 있어야하기때문에 일단 보류.. (운영 테이블에서 FK설정 안하고싶음..)

2024-09-28 12:30 UTC, Gyaak commented on backend/src/main/java/kernel360/techpick/feature/pick/repository/PickTagRepository.java
> +	boolean existsByTag_Id(Long tag_id);
수정 예정

2024-09-28 12:34 UTC, kimminkyeu commented on backend/src/main/java/kernel360/techpick/feature/tag/controller/TagController.java
> +	private Long getUserId(Authentication authentication) {
확인. 이건 좀 더 검토가 필요해보임

2024-09-28 12:35 UTC, kimminkyeu commented on backend/src/main/java/kernel360/techpick/feature/tag/service/TagService.java
> +		validateTagNameExists(userId, request.name());
그럼 validator를 따로 빼는 건 어떨지?

2024-09-28 12:38 UTC, kimminkyeu commented on backend/src/main/java/kernel360/techpick/feature/tag/service/TagService.java
> +		validateTagHasPick(tagId);
picktag에서 직접 지워주는 것도 괜찮을 듯. 그럼 pick 삭제, tag 삭제 서비스 구현시 추가해주면 될 듯 :smiley: 
FK 설정 안하고 싶다는 말에 공감함...

2024-09-28 12:46 UTC, kimminkyeu commented
p3: 우리 Link controller는 없어져도 될 것 같음. link는 api를 열어줄 필요가 없어 보이는데, 의견 부탁

2024-09-28 12:50 UTC, Gyaak commented
> p3: 우리 Link controller는 없어져도 될 것 같음. link는 api를 열어줄 필요가 없어 보이는데, 의견 부탁

관리자가 직접 link를 등록하거나 조회할 수도 있다고 생각하여 controller를 별도로 둠

2024-09-28 12:54 UTC, Gyaak commented on backend/src/main/java/kernel360/techpick/feature/pick/repository/PickTagRepository.java
> +	boolean existsByTag_Id(Long tag_id);
현재 PR에서 다룰 내용은 아니라고 생각되어 별도 이슈 #72 등록 후 수정 예정

2024-09-28 12:55 UTC, kimminkyeu commented on backend/src/main/java/kernel360/techpick/feature/pick/repository/PickTagRepository.java
> +	boolean existsByTag_Id(Long tag_id);
이슈 확인하였음

2024-09-28 13:12 UTC, Gyaak commented on backend/src/main/java/kernel360/techpick/feature/tag/service/TagService.java
> +		validateTagNameExists(userId, request.name());
차라리 그게 좋을것같음 수정 예정

2024-09-28 14:22 UTC, Gyaak commented on backend/src/main/java/kernel360/techpick/feature/tag/service/TagService.java
> +			tagMapper.updateTag(req, targetTag);
태그 순서 검증 로직 추가 완료

2024-09-28 14:28 UTC, kimminkyeu commented on backend/src/main/java/kernel360/techpick/feature/tag/service/TagService.java
> +		// TODO: PickTagProvider 구현되면 PickTagProvider를 의존하도록 리팩토링 필요
p1: tagId가 pickTagId로 넘겨졌습니다.
```suggestion
	pickTagRepository.deleteByTag_Id(Long tag_id);
```

2024-09-28 14:32 UTC, Gyaak commented on backend/src/main/java/kernel360/techpick/feature/tag/service/TagService.java
> +		// TODO: PickTagProvider 구현되면 PickTagProvider를 의존하도록 리팩토링 필요
수정완료 확인부탁

2024-09-28 14:33 UTC, kimminkyeu commented on backend/src/main/java/kernel360/techpick/feature/tag/service/TagService.java
> +		// TODO: PickTagProvider 구현되면 PickTagProvider를 의존하도록 리팩토링 필요
확인 완료. 변경 사항 확인 후 approve 드리겠습니다. :+1:

2024-09-28 14:36 UTC, kimminkyeu commented on backend/src/main/java/kernel360/techpick/feature/tag/model/TagProvider.java
> +		return tag.map(value -> value.getOrder() + 1).orElse(1);
ㅋㅋ 1씩 더하는 거 눈물 나네요 ㅠㅠㅠ

2024-09-28 14:36 UTC, kimminkyeu commented on backend/src/main/java/kernel360/techpick/feature/tag/service/TagService.java
> +		int lastOrder = tagProvider.getLastOrderByUSerId(userId);
USerId --> UserId 오타 났습니다!

2024-09-28 14:38 UTC, Gyaak commented on backend/src/main/java/kernel360/techpick/feature/tag/service/TagService.java
> +		int lastOrder = tagProvider.getLastOrderByUSerId(userId);
수정완료

2024-09-28 14:39 UTC, kimminkyeu commented on backend/src/main/java/kernel360/techpick/feature/tag/model/TagProvider.java
> +		return tag.map(value -> value.getOrder() + 1).orElse(1);
태그가 아무것도 없으면 0을 줘야 하는 것 아닌지

2024-09-28 14:43 UTC, Gyaak commented on backend/src/main/java/kernel360/techpick/feature/tag/model/TagProvider.java
> +		return tag.map(value -> value.getOrder() + 1).orElse(1);
order를 0부터 시작할건지 1부터 시작할건지 문제인데...
0부터 시작하는게 더 편할까요?

2024-09-28 14:49 UTC, Gyaak commented on backend/src/main/java/kernel360/techpick/feature/tag/model/TagProvider.java
> +		return tag.map(value -> value.getOrder() + 1).orElse(1);
크게 중요한 것은 아니라고 생각해서 0부터 시작하도록 수정
그리고 tag order가 음수값인 경우 검증하는 로직 추가

2024-09-28 14:53 UTC, kimminkyeu commented on backend/src/main/java/kernel360/techpick/feature/tag/validator/TagValidator.java
> +		if (tag == null || !Objects.equals(userId, tag.getUser().getId())) {
### 이건 추후 제가 한번 추가해볼 까 고민되어서 남기는 글이니 참고만 부탁.

tag 가 null 이 들어오는 것은, 사용자 실수보단 개발자 실수에 가깝다고 봄.
이 함수는 반드시 tag가 null이 들어오지 않는다고 생각하고 Assertion을 날리는 것이 필요할 것 같다.
함수의 정상적 진입 조건과 반환 조건 Assersion을 따로 apiExeption을 만들고, 이를 "즉시 해결 필요한 에러"로 처리하면 좋을 것 같다.

2024-09-28 14:56 UTC, Gyaak commented on backend/src/main/java/kernel360/techpick/feature/tag/validator/TagValidator.java
> +		if (tag == null || !Objects.equals(userId, tag.getUser().getId())) {
Assrtions으로 따로 빼면 매우 좋을거같음
저 메소드에서는 `tag == null` 조건을 안넣으면 NPE가 발생할 수 때문에 추가한것

2024-09-28 14:58 UTC, kimminkyeu commented on backend/src/main/java/kernel360/techpick/feature/tag/validator/TagValidator.java
> +		if (tag == null || !Objects.equals(userId, tag.getUser().getId())) {
현재 상황에서 tag == null은 최선의 선택인 것 같음.
지금 수정 안해도 된다고 생각함. :thumbsup

2024-09-28 15:01 UTC, kimminkyeu approved these changes
LGTM !! 리뷰 마치겠습니다 :)
코드가 가독성이 좋아서, 리뷰를 더 세밀하게 할 수 있었습니다.  늦은 시간까지 고생 많으셨습니다 :)

2024-09-28 15:02 UTC, kimminkyeu commented
대화 resolve는 상원님도 확인이 끝난 후에 한번에 해주시면 감사하겠습니다~

2024-09-28 16:05 UTC, sangwonsheep reviewed
고생하셨습니다! 코멘트 남겼으니 확인 부탁드려요!
리뷰 남기신 부분들 모두 확인했습니다.

2024-09-28 16:05 UTC, sangwonsheep commented on backend/src/main/java/kernel360/techpick/feature/tag/validator/TagValidator.java
> +		if (tag == null || !Objects.equals(userId, tag.getUser().getId())) {
p3: tag null 체크를 아래와 같은 코드로 변경하는 것은 어떤지
```java
tag == null -> Objects.isNull(tag)
```

2024-09-28 16:16 UTC, sangwonsheep commented on backend/src/main/java/kernel360/techpick/feature/tag/model/TagProvider.java
> +		return tag.map(value -> value.getOrder() + 1).orElse(1);
p2: orElse 대신 orElseGet 사용은 어떤지?
orElse : null이든 말든 항상 호출
orElseGet : null일 경우에만 호출
[참고 사이트](https://cfdf.tistory.com/34)

2024-09-28 16:34 UTC, Gyaak commented on backend/src/main/java/kernel360/techpick/feature/tag/model/TagProvider.java
> +		tagRepository.findAllByUser_Id(userId)
연관관계의 key로 조회하기 위해서는 쿼리 메소드를 **_Id로 해야함

2024-09-28 16:34 UTC, Gyaak commented on backend/src/main/java/kernel360/techpick/feature/tag/repository/TagRepository.java
> +	Optional<Tag> findFirstByUser_IdOrderByOrderDesc(Long user_id);
위와 마찬가지

2024-09-28 16:38 UTC, Gyaak commented
@sangwonsheep
`tag == null`이 `Objects.isNull(tag)`보다 더 가독성이 좋다고 생각되어 변경하지 않음
reply가 안보여서 코멘트로 남김

2024-09-28 16:39 UTC, Gyaak commented on backend/src/main/java/kernel360/techpick/feature/tag/validator/TagValidator.java
> +		if (tag == null || !Objects.equals(userId, tag.getUser().getId())) {
`tag == null` 이 `Objects.isNull(tag)`보다 가독성이 더 좋다고 판단되어 수정하지 않음

2024-09-28 16:50 UTC, Gyaak commented on backend/src/main/java/kernel360/techpick/feature/tag/model/TagProvider.java
> +		return tag.map(value -> value.getOrder() + 1).orElse(1);
수정완료
생각보다 성능차이가 많이 나네요
[Java Optional – orElse() vs orElseGet() -Bauldung](https://www.baeldung.com/java-optional-or-else-vs-or-else-get#jmh%20benchmark)

2024-09-28 17:24 UTC, Gyaak commented
@sangwonsheep @kimminkyeu 

기존 tag update 로직의 경우 validator가 아닌 service에서 예외를 던지는 것이 매우 거슬림
그래서 validator를 통해 검증하도록 변경했는데.. 이 경우 map에 없으면 null값이 validator로 전달됨
null값이 전달되는것을 의도하게 되는데 이거에 대한 의견을 듣고 싶어요
1. null값을 전달하더라도 validator에서 처리
2. 그냥 service에서 예외처리(기존코드+상원님 의견(else제거))
3. validator에 Map과 UpdateRequest를 파라미터로 받는 별로 검증 메소드 추가하여 검증

`TagService.java`
```
@Transactional
	public List<TagResponse> updateTagList(Long userId, List<TagUpdateRequest> tagUpdateRequests) throws
		ApiTagException {

		Map<Long, Tag> tagMap = tagProvider.getTagMapByUserId(userId);

		for (var req : tagUpdateRequests) {
			// 만약 자신의 태그가 아니라면 tagMap.get(req.id()) == null
			tagValidator.validateTagAccess(userId, tagMap.get(req.id()));
			tagMapper.updateTag(req, tagMap.get(req.id()));
		}

		// 수정한 태그들 중 order 가 중복되는지 검증
		tagValidator.validateTagOrder(tagMap);

		return tagProvider.saveAll(tagMap.values())
			.stream()
			.map(tagMapper::createTagResponse)
			.toList();
	}
```

`TagValidator`
```
public void validateTagAccess(Long userId, Tag tag) throws ApiTagException {

		if (tag == null || !Objects.equals(userId, tag.getUser().getId())) {
			throw ApiTagException.UNAUTHORIZED_TAG_ACCESS();
		}
	}
```

2024-09-29 03:38 UTC, kimminkyeu commented
**제가 볼땐 `tagMap`이 이 고민의 원인.**
   `Map` 자료구조가 `Service`에서 사용되서 생기는 고민인 것 같아요.
    저는 `Map`은 이건 상세 구현에 해당된다고 생각합니다.
    서비스는 읽었을 때 `아 모든 Request들을 돌아서 업데이트 치는 구나~` 정도만 보이는게 할 수 없을까 싶어요.

이 경우는, `tagMap` 을 한번 캡슐화해서 자동 검사해주는 게 어떨까 싶어요.
- 참고 : [EncapsulatedCollection](https://martinfowler.com/bliki/EncapsulatedCollection.html)

이렇게 하면 어떨까요?
```java
/* TagProvider.java */
public UserTags getTagsByUserId(Long userId) {
		Map<Long, Tag> tagMap = new HashMap<>();
			.forEach(tag -> tagMap.put(tag.getId(), tag));
		return UserTagMap.fromList( tagRepository.findAllByUser_Id(userId) );
}

// 한 사용자의 tag들을 담는 일종의 DTO 클래스
/* UserTags.java */
public class UserTags {
  private Long userId;
  private Map<String, Tag> map;
 
  public Long getOwnerId() {
     return this.userId;
  }  

  public Tag getTagById( tagId ) {
     if (!map.contains(tagId)) { 
        throw ApiTagException.UNAUTHORIZED_TAG_ACCESS();
     } 
  }
 
  public static UserTags fromList(List<Tag> tags) { 
     // ... 생성자 정적 팩토리 메소드
  }
}
```

2024-09-29 03:44 UTC, kimminkyeu commented
아 그리고 tagMapper가 tag 정보를 업데이트하던데 이 부분은 mapper에서 안하고 그냥 엔티티에서 직접 호출하면 되지 않나요

2024-09-29 03:46 UTC, kimminkyeu commented
또 request 에서 tagId가 null로 들어왔을 때 예외 처리가 필요해보입니다.

2024-09-29 05:08 UTC, sangwonsheep commented on backend/src/main/java/kernel360/techpick/feature/tag/repository/TagRepository.java
> +	Optional<Tag> findFirstByUser_IdOrderByOrderDesc(Long user_id);
```java
boolean existsByUser_IdAndName(Long userId, String name);

boolean existsByUserIdAndName(Long userId, String name);
```
이렇게 사용하면 조회가 안되는건지?

2024-09-29 05:45 UTC, Gyaak commented on backend/src/main/java/kernel360/techpick/feature/tag/repository/TagRepository.java
> +	Optional<Tag> findFirstByUser_IdOrderByOrderDesc(Long user_id);
지금 다시 테스트 해봤는데.. camel case도 되네요 수정예정

2024-09-29 05:56 UTC, Gyaak commented
@kimminkyeu 
일단 `Map` 타입이 서비스에서 돌아다니는게 문제네요
최대한 Provider 안쪽에서 처리하고 서비스에서는 원하는 객체만 받도록 하는게 맞을거같네요

`UserTag`와 같은 wrapper를 추가로 사용하는것에 대해서는 저는 별로 좋아하지 않아서(개인취향)
최대한 Provider에서 처리하도록 해보고 영 방법이 안보이면 그때 고려할 예정

그리고 객체에 대한 모든 책임을 Provider가 가질 경우 객체 검증을 Validator로 분리하지 않고 Provider가 갖게 하는것도 방법일 수 있겠네요!

2024-09-29 05:59 UTC, kimminkyeu commented
네! 저도 Provider로 한번에 할 수 있음 가장 좋다고 생각합니다 :+1:

2024-09-29 11:07 UTC, Gyaak commented
@sangwonsheep @kimminkyeu 

| request 에서 tagId가 null로 들어왔을 때 예외 처리가 필요해보입니다.
-> dto에서 bean validation으로 검증해야하는것이 아닌가 라고 생각되어 service에 검증 로직은 넣지 않았는데
추가 의견 있으면 부탁드림..(어느게 더 좋은 방법일지 판단이 잘 안서네요)

Map 사용 안하는 쪽으로 리팩토링 했습니다.
근데 또 작성하고 보니.. service 쪽 로직이 복잡해졌네요..

결국 어디선가는 **_update요청한 태그가 정말 본인이 작성한게 맞는지_** 검증하는 과정이 필요한데..
Provider에서 같이 처리하려면, Provider가 userTag(사용자가 등록한 태그 리스트 혹은 멥)를 계속 들고있어야함.

이렇게 될 경우 Provider를 create delete 발생 시 Provider와 db의 userTag 정보 동기화 같은 로직도 필요할거 같아서
**Provider에서는 db 객체 제공**만 하고,
provider에서 받은 리스트와 요청에서 받은 업데이트 리스트를 **validator로 넘겨서 검증 및 조회**하는 로직으로 수정했습니다...
결국 맨 처음 방식에서 크게 달라지지 않았네요..


`TagService.java`
```
@Transactional
public List<TagResponse> updateTagList(Long userId, List<TagUpdateRequest> tagUpdateRequests) throws
ApiTagException {

// immutable list로 들어올 경우 sort가 불가능해 ArrayList로 변환
// 항상 mutable list라는것이 보장된다면 삭제해주세요..
List<TagUpdateRequest> mutableTagUpdateRequests = new ArrayList<>(tagUpdateRequests);
mutableTagUpdateRequests.sort(Comparator.comparingLong(TagUpdateRequest::id));

List<Tag> userTagList = tagProvider.findAllByUserIdOrderByTagId(userId);

int idx = 0;
for (var req : mutableTagUpdateRequests) {
	idx = tagValidator.findUpdateTagIdx(idx, req, userTagList);
	tagMapper.updateTag(req, userTagList.get(idx));
	idx++;
}

return tagProvider.saveAll(userTagList)
	.stream()
	.map(tagMapper::createTagResponse)
	.toList();
}
```

`TagValidator.java`
```
// 업데이트 대상이 되는 태그의 userTagList에서의 index 반환
// 만약 userTagList에 업데이트 하려는 태그가 존재하지 않으면,
// 본인이 등록하지 않은 태그에 접근하려는 것이므로 ApiTagException.UNAUTHORIZED_TAG_ACCESS() 발생
public int findUpdateTagIdx(int startIdx, TagUpdateRequest req, List<Tag> userTagList) throws ApiTagException {

for (int i = startIdx; i < userTagList.size(); i++) {
	if (req.id().equals(userTagList.get(i).getId())) {
		return i;
	}
}
throw ApiTagException.UNAUTHORIZED_TAG_ACCESS();
}
```

2024-09-29 11:26 UTC, Gyaak commented
UserTag 사용하는 방향으로 수정중

2024-09-29 11:44 UTC, Gyaak commented
| request 에서 tagId가 null로 들어왔을 때 예외 처리가 필요해보입니다.
-> dto에서 bean validation으로 검증해야하는것이 아닌가 라고 생각되어 service에 검증 로직은 넣지 않았는데
추가 의견 있으면 부탁드림..(어느게 더 좋은 방법일지 판단이 잘 안서네요)

Tag Update 로직 관련해서 민규님 의견을 참고하여 Update 전용 클래스를 추가했습니다.
@sangwonsheep @kimminkyeu 확인 부탁드려요

2024-09-29 12:04 UTC, kimminkyeu commented on backend/src/main/java/kernel360/techpick/feature/tag/model/TagProvider.java
> +		return tag.map(value -> value.getTagOrder() + 1).orElseGet(() -> 0);
순서 0, 1 관계 없이 `getTagOrder()+1` 을 안해야 할 듯함
- 만약 0부터 시작
  1. 태그 없음 -> last = -1
  2. 태그 1개, 첫번재 순서는 0 -> last = 0;
  3. 태그 2개, 순서는 0, 1 -> last = 1;
- 만약 1부터 시작
  1. 태그 없음 -> last = 0
  2. 태그 1개, 첫번재 순서는 1 -> last = 1;
  3. 태그 2개, 순서는 1, 2 -> last = 2;

2024-09-29 12:06 UTC, kimminkyeu approved these changes
LGTM. 지금 방식도 좋은 것 같습니다. 고생하셨습니다.

2024-09-29 12:07 UTC, kimminkyeu commented
> | request 에서 tagId가 null로 들어왔을 때 예외 처리가 필요해보입니다. -> dto에서 bean validation으로 검증해야하는것이 아닌가 라고 생각되어 service에 검증 로직은 넣지 않았는데 추가 의견 있으면 부탁드림..(어느게 더 좋은 방법일지 판단이 잘 안서네요)
> 
> Tag Update 로직 관련해서 민규님 의견을 참고하여 Update 전용 클래스를 추가했습니다. @sangwonsheep @kimminkyeu 확인 부탁드려요

넵 dto에서 null 체크 해주면 되겠네요. 서비스는 안넣는게 맞는거 같습니다!

2024-09-29 12:27 UTC, YunNote commented on backend/src/main/java/kernel360/techpick/feature/tag/controller/TagController.java
> +	private Long getUserId(Authentication authentication) {
말씀해주시는 부분이 SecurityContextHolder.getContext.setAuthentication(xx)를 통해 세팅한 해당 값을 
컨트롤러에서 받아서 꺼내쓴다는 말씀이신가요 ???
설명 조금 더 부탁드리겠씁니다 !

2024-09-29 12:29 UTC, Gyaak commented on backend/src/main/java/kernel360/techpick/feature/tag/model/TagProvider.java
> +		return tag.map(value -> value.getTagOrder() + 1).orElseGet(() -> 0);
현재 로직이 태그가 존재하지 않을때만 0을 반환하고, 태그가 하나라도 존재하면 해당 태그의 오더 +1 값을 반환함

2024-09-29 12:31 UTC, YunNote commented on backend/src/main/java/kernel360/techpick/feature/tag/service/TagService.java
> +		validateTagNameExists(userId, request.name());
생성정책 < createPolicy() 로 판 후 해당 메서드 내부에서 상세 정책에 대해 Exception을 발생시키는 건 어떻게 생각하세요 ??

2024-09-29 12:32 UTC, YunNote commented on backend/src/main/java/kernel360/techpick/feature/pick/repository/PickTagRepository.java
> +	boolean existsByTag_Id(Long tag_id);
해당 부분 메서드명에서 언더스코어 표기 -> 카멜케이스로 변경도 추가되면 좋을듯합니다

2024-09-29 12:38 UTC, YunNote commented on backend/src/main/java/kernel360/techpick/feature/tag/validator/TagValidator.java
> +		if (tag == null || !Objects.equals(userId, tag.getUser().getId())) {
해당 tag == null or Objects.isNull(tag) 상황에 다라 다르겠지만 

tag == null 이 간단한 프로젝트에서는 괜찮지만 협업시 코드에 의도가 더 명확하게 나타나기 때문에 Objects.isNull을 사용해보시는것을 추천드리고 싶습니다.

2024-09-29 12:56 UTC, YunNote commented
TokenAuthenticationFilte.java 에서 ACCESS_TOKEN_KEY 를 key 로 사용하시는데 사용하시는 부분에 차라리 이미 static 상수로 등록된 ACCESS_TOKEN_KEY를 사용하는것이 어떨까요 추가로 equals 비교시에는 상수가 앞으로 오는것이 더 좋아보입니다.

2024-09-29 12:59 UTC, YunNote commented
config에서 특정 값들을 가져오는 부분들은 configurationproperties에 대해서 한번 찾아보시면 좋을듯합니다

2024-09-29 12:59 UTC, YunNote commented
common.model <<은 사용하지 않는 패키지로 삭제되면 어떨까 싶습니다 사용하지 않는 import구문들도 추가로 제거되면 좋을거 같아요 !

2024-09-29 13:00 UTC, sangwonsheep approved these changes
LGTM, 민규님 의견에 동의합니다.

2024-09-29 13:30 UTC, Gyaak commented on backend/src/main/java/kernel360/techpick/feature/tag/controller/TagController.java
> +	private Long getUserId(Authentication authentication) {
@YunNote 
네 맞습니다. `TokenAuthenticationFilter.java`에서 사용자 인증시 securitycontext에 저장한 authentication 객체를 이용하고 있습니다.
하지만, Authentication 객체로 받는게 아니라 그 안에 있는 (Long)userId로 바로 받아올 수 있는방법이 없을지 고민중이었습니다.

2024-09-29 13:44 UTC, Gyaak commented
> TokenAuthenticationFilte.java 에서 ACCESS_TOKEN_KEY 를 key 로 사용하시는데 사용하시는 부분에 차라리 이미 static 상수로 등록된 ACCESS_TOKEN_KEY를 사용하는것이 어떨까요 추가로 equals 비교시에는 상수가 앞으로 오는것이 더 좋아보입니다.
> 
> `private String findCookieByKey` 해당 메서드 입니다

-> 수정하겠습니다. token key는 거의 변하지 않는 값이니 상수로 처리하는것이 더 좋은 방법인것 같습니다.

---

> common.model <<은 사용하지 않는 패키지로 삭제되면 어떨까 싶습니다 사용하지 않는 import구문들도 추가로 제거되면 좋을거 같아요 !

->  `/core/model/common/` 패키지를 말씀하시는걸까요? 해당 패키지에는 생성/수정 시간을 기록하는 TimeTracking 엔티티(BaseEntity 역할)가 있습니다. 혹시 다른 패키지를 말씀하신거였다면 알려주세요..! ㅠ

2024-09-30 01:50 UTC, merged