Refactor: RSS Exception 처리
Kernel360/F2-TECHPICK pull request #81
Opened 2024-09-30 05:13 UTC by sangwonsheep

- Close #75 

## What is this PR? 🔍

- 기능 : RSS 예외 처리
- issue : #75 

## Changes 📝
- RSS error code, exception 추가
- RSS service에서 사용 중이던 repository -> provider로 분리
- RSS service에 예외 처리 코드 추가 

## Precaution
- Retry 필요할 지 의문

2024-09-30 05:45 UTC, Gyaak requested changes
PR제목이 RssProvider 분리 관련된 내용을 포함해야할것 같음
-> 별도 이슈로 관리되는게 맞지 않았을지(의견)

2024-09-30 05:45 UTC, Gyaak commented on backend/src/main/java/kernel360/techpick/feature/rss/service/RssService.java
> +
p1: 중간에 `RestClientException` 발생하면 뒤쪽 크롤링 데이터는 db에 제대로 저장되지 않을거같음 수정필요

---

p2: 발생한 예외에 따라 복구가능한 경우는 리트라이 로직이 필요할 것 같음
- 복구 불가능한 예외 ex) rss 형식이 맞지 않음
- 복구 가능한 예외 ex) 일시적인 타임아웃

2024-09-30 06:47 UTC, kimminkyeu commented on backend/src/main/java/kernel360/techpick/core/exception/feature/rss/ApiRssErrorCode.java
> +	RSS_NOT_FOUND("RS-000", HttpStatus.NOT_FOUND, "RSS 피드 렌더링 오류 또는 RSS 지원하지 않는 사이트");
p2: 에러 레벨 추가된 것, 디렉토리 변경된 것은 제가 머지 후에 수정하겠음.

2024-09-30 06:52 UTC, kimminkyeu commented on backend/src/main/java/kernel360/techpick/feature/rss/service/RssService.java
> +
rss 형식이 틀린 경우와 일시적 타임아웃을 구분하는 것에 동감.
다만 리트라이도 MAX_RETRY를 넘어서면, 복구 불가능한 예외로 처리하고 끝내야 할 듯

2024-09-30 06:53 UTC, kimminkyeu approved these changes
코멘트 확인 부탁드립니다. 고생하셨습니다.

2024-10-01 06:08 UTC, sangwonsheep commented on backend/src/main/java/kernel360/techpick/feature/rss/service/RssService.java
> +
retry 로직 추가, Exception 발생 시 뒤쪽 크롤링 데이터 추가되도록 수정 완료

2024-10-01 06:10 UTC, sangwonsheep commented on backend/src/main/java/kernel360/techpick/feature/rss/service/RssService.java
> +
복구 가능, 불가능은 retry를 통해서 해결할 수 있는 것인지? 현재로썬 url이 잘못되어도 형식이 잘못되어도 `RestClientException` 발생

2024-10-01 06:13 UTC, sangwonsheep commented
`RestClientException` 발생 시 기존에는 throw를 통해 custom exception을 던졌는데, 현재는 log만 찍도록 변경.
중간에 문제가 있는 블로그는 3회 retry 후 `RestClientException` 발생, 그 이후의 블로그들은 rss 데이터 수집이 필요하기 때문에 이 방식이 맞는지 의문

2024-10-01 06:37 UTC, sangwonsheep commented
현재 무신사 rss는 형식이 깨져서 rss 수집이 되지 않음. 오류 상황 발생을 위해 url 추가해둔 상황

2024-10-01 06:47 UTC, Gyaak approved these changes
고생하셨습니다.
나중에 blog 별로 별도 메소드에서 처리하도록 리팩토링하면
병렬처리도 고려해볼 수 있고, error logging에도 용이할것 같아요

2024-10-01 07:34 UTC, merged